ALTER TABLE "users"
ADD COLUMN IF NOT EXISTS "pin_hash" TEXT,
ADD COLUMN IF NOT EXISTS "last_login" TIMESTAMP(3);

ALTER TABLE "user_outlets"
ADD COLUMN IF NOT EXISTS "status" "Status" NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
