import 'dotenv/config';
import express from 'express';
import cors, { type CorsOptions } from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { Prisma } from '@prisma/client';
import { allow, ApiError, assertOutlet, asyncRoute, auth, dayRange, money, prisma } from './lib.js';
import { discountAmount, priceCart, validateCoupon } from './discount.js';

const defaultCorsOrigins = [
  'http://localhost',
  'http://localhost:5173',
  'http://192.168.1.24:5173',
  'http://103.253.244.190:5173',
  'capacitor://localhost',
  'ionic://localhost'
];
function parseOrigins(value?: string) {
  return (value || '')
    .split(',')
    .map(origin => origin.trim())
    .filter(Boolean);
}
function normalizeOrigin(origin: string) {
  return origin.trim().replace(/\/$/, '').toLowerCase();
}
const corsOrigins = [
  ...defaultCorsOrigins,
  ...parseOrigins(process.env.WEB_URL),
  ...parseOrigins(process.env.CORS_ORIGINS)
]
  .map(normalizeOrigin)
  .filter(Boolean);
const allowedCorsOrigins = new Set(corsOrigins);
const corsOptions: CorsOptions = {
  origin(origin, callback) {
    if (!origin || allowedCorsOrigins.has(normalizeOrigin(origin))) return callback(null, true);
    return callback(new ApiError(403, `Origin ${origin} tidak diizinkan oleh CORS`));
  },
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
  optionsSuccessStatus: 204
};

const app=express(); app.use(cors(corsOptions)); app.use(express.json());
const api=express.Router(); app.use('/api',api);
api.get('/health',(_q,r)=>r.json({ok:true}));

api.post('/auth/login',asyncRoute(async(req,res)=>{
  const {username,password}=z.object({username:z.string(),password:z.string()}).parse(req.body);
  const user=await prisma.user.findUnique({where:{username},include:{outlets:true}});
  if(!user||user.status!=='ACTIVE'||!await bcrypt.compare(password,user.passwordHash)) throw new ApiError(401,'Username atau password salah');
  const payload={id:user.id,role:user.role,outletIds:user.outlets.map(x=>x.outletId)};
  res.json({token:jwt.sign(payload,process.env.JWT_SECRET||'dev-secret',{expiresIn:'12h'}),user:{id:user.id,name:user.name,role:user.role,outletIds:payload.outletIds}});
}));
api.get('/auth/me',auth,asyncRoute(async(req,res)=>res.json(await prisma.user.findUnique({where:{id:req.user!.id},select:{id:true,name:true,username:true,role:true,outlets:{select:{outlet:true}}}}))));

api.use(auth);
api.get('/outlets',asyncRoute(async(req,res)=>res.json(await prisma.outlet.findMany({where:req.user!.role==='OWNER'?{}:{id:{in:req.user!.outletIds}},orderBy:{name:'asc'}}))));
api.post('/outlets',allow('OWNER'),asyncRoute(async(req,res)=>res.status(201).json(await prisma.outlet.create({data:z.object({code:z.string().min(2),name:z.string().min(2),address:z.string().optional(),phone:z.string().optional()}).parse(req.body)}))));
api.put('/outlets/:id',allow('OWNER'),asyncRoute(async(req,res)=>res.json(await prisma.outlet.update({where:{id:String(req.params.id)},data:z.object({code:z.string().min(2).optional(),name:z.string().min(2).optional(),address:z.string().nullable().optional(),phone:z.string().nullable().optional(),status:z.enum(['ACTIVE','INACTIVE']).optional()}).parse(req.body)}))));
api.delete('/outlets/:id',allow('OWNER'),asyncRoute(async(req,res)=>res.json(await prisma.outlet.update({where:{id:String(req.params.id)},data:{status:'INACTIVE'}}))));

const printerBody=z.object({outletId:z.string(),printerName:z.string().min(2),printerType:z.enum(['THERMAL']).default('THERMAL'),connectionType:z.enum(['BLUETOOTH','USB','NETWORK','BROWSER']),paperSize:z.enum(['MM58','MM80']).default('MM58'),ipAddress:z.string().nullable().optional(),port:z.coerce.number().int().positive().nullable().optional(),bluetoothAddress:z.string().nullable().optional(),usbVendorId:z.string().nullable().optional(),usbProductId:z.string().nullable().optional(),isCustomerReceipt:z.coerce.boolean().default(false),isKitchenPrinter:z.coerce.boolean().default(false),status:z.enum(['ACTIVE','INACTIVE']).default('ACTIVE')});
api.get('/printers',allow('OWNER','SUPERVISOR','CASHIER'),asyncRoute(async(req,res)=>{const where:any={};if(req.query.outlet_id){assertOutlet(req,String(req.query.outlet_id));where.outletId=String(req.query.outlet_id);}else if(req.user!.role!=='OWNER')where.outletId={in:req.user!.outletIds};res.json(await prisma.printer.findMany({where,include:{outlet:true},orderBy:{createdAt:'desc'}}));}));
api.post('/printers',allow('OWNER'),asyncRoute(async(req,res)=>{const d=printerBody.parse(req.body);assertOutlet(req,d.outletId);res.status(201).json(await prisma.printer.create({data:d,include:{outlet:true}}));}));
api.put('/printers/:id',allow('OWNER'),asyncRoute(async(req,res)=>{const d=printerBody.partial().parse(req.body);const existing=await prisma.printer.findUnique({where:{id:String(req.params.id)}});if(!existing)throw new ApiError(404,'Printer tidak ditemukan');assertOutlet(req,d.outletId||existing.outletId);res.json(await prisma.printer.update({where:{id:existing.id},data:d,include:{outlet:true}}));}));
api.delete('/printers/:id',allow('OWNER'),asyncRoute(async(req,res)=>res.json(await prisma.printer.update({where:{id:String(req.params.id)},data:{status:'INACTIVE'}}))));

const categoryBody=z.object({name:z.string().min(2),description:z.string().nullable().optional(),sortOrder:z.coerce.number().int().default(0),status:z.enum(['ACTIVE','INACTIVE']).default('ACTIVE')});
api.get('/categories',asyncRoute(async(_q,res)=>res.json(await prisma.category.findMany({orderBy:[{sortOrder:'asc'},{name:'asc'}]}))));
api.post('/categories',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>res.status(201).json(await prisma.category.create({data:categoryBody.parse(req.body)}))));
api.put('/categories/:id',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>res.json(await prisma.category.update({where:{id:String(req.params.id)},data:categoryBody.partial().parse(req.body)}))));
api.delete('/categories/:id',allow('OWNER'),asyncRoute(async(req,res)=>res.json(await prisma.category.update({where:{id:String(req.params.id)},data:{status:'INACTIVE'}}))));

const variantGroupBase=z.object({name:z.string().min(2),description:z.string().nullable().optional(),minSelect:z.coerce.number().int().min(0).default(0),maxSelect:z.coerce.number().int().min(1).default(1),required:z.coerce.boolean().default(false),status:z.enum(['ACTIVE','INACTIVE']).default('ACTIVE'),options:z.array(z.object({name:z.string().min(1),additionalPrice:z.coerce.number().nonnegative().default(0),hpp:z.coerce.number().nonnegative().default(0),sortOrder:z.coerce.number().int().default(0),status:z.enum(['ACTIVE','INACTIVE']).default('ACTIVE')})).optional()});
const variantGroupBody=variantGroupBase.refine(d=>d.maxSelect>=d.minSelect,{message:'Maksimal pilihan harus >= minimal pilihan'});
api.get('/variant-groups',asyncRoute(async(_q,res)=>res.json(await prisma.variantGroup.findMany({include:{options:{orderBy:{sortOrder:'asc'}}},orderBy:{name:'asc'}}))));
api.post('/variant-groups',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>{const d=variantGroupBody.parse(req.body);const {options,...data}=d;res.status(201).json(await prisma.variantGroup.create({data:{...data,options:{create:options||[]}},include:{options:true}}));}));
api.put('/variant-groups/:id',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>res.json(await prisma.variantGroup.update({where:{id:String(req.params.id)},data:variantGroupBase.omit({options:true}).partial().parse(req.body),include:{options:{orderBy:{sortOrder:'asc'}}}}))));
api.delete('/variant-groups/:id',allow('OWNER'),asyncRoute(async(req,res)=>res.json(await prisma.variantGroup.update({where:{id:String(req.params.id)},data:{status:'INACTIVE'}}))));
api.post('/variant-groups/:id/options',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>res.status(201).json(await prisma.variantOption.create({data:{variantGroupId:String(req.params.id),...z.object({name:z.string().min(1),additionalPrice:z.coerce.number().nonnegative().default(0),hpp:z.coerce.number().nonnegative().default(0),sortOrder:z.coerce.number().int().default(0),status:z.enum(['ACTIVE','INACTIVE']).default('ACTIVE')}).parse(req.body)}}))));
api.put('/variant-options/:id',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>res.json(await prisma.variantOption.update({where:{id:String(req.params.id)},data:z.object({name:z.string().min(1).optional(),additionalPrice:z.coerce.number().nonnegative().optional(),hpp:z.coerce.number().nonnegative().optional(),sortOrder:z.coerce.number().int().optional(),status:z.enum(['ACTIVE','INACTIVE']).optional()}).parse(req.body)}))));
api.delete('/variant-options/:id',allow('OWNER'),asyncRoute(async(req,res)=>res.json(await prisma.variantOption.update({where:{id:String(req.params.id)},data:{status:'INACTIVE'}}))));

const outletPricingInput=z.object({outletId:z.string(),isAvailable:z.coerce.boolean().default(true),outletPrice:z.coerce.number().nonnegative().nullable().optional(),outletHpp:z.coerce.number().nonnegative().nullable().optional(),status:z.enum(['ACTIVE','INACTIVE']).default('ACTIVE')});
const productInput=z.object({name:z.string().min(2),categoryId:z.string().optional(),category:z.string().optional(),description:z.string().optional(),imageUrl:z.string().url().optional().or(z.literal('')),basePrice:z.coerce.number().nonnegative().optional(),baseHpp:z.coerce.number().nonnegative().optional(),status:z.enum(['ACTIVE','INACTIVE']).default('ACTIVE'),variantGroupIds:z.array(z.string()).default([]),outletIds:z.array(z.string()).default([]),outletPricing:z.array(outletPricingInput).optional(),variants:z.array(z.object({variantName:z.string(),sellingPrice:z.coerce.number().nonnegative(),hpp:z.coerce.number().nonnegative()})).optional()});
const productInclude={categoryRef:true,variants:true,addons:true,outlets:{include:{outlet:true},orderBy:{outlet:{name:'asc' as const}}},variantGroups:{orderBy:{sortOrder:'asc' as const},include:{group:{include:{options:{orderBy:{sortOrder:'asc' as const},include:{outlets:{include:{outlet:true}}}}}}}}};
async function categoryName(categoryId?:string,category?:string){if(categoryId){const c=await prisma.category.findUnique({where:{id:categoryId}});if(!c)throw new ApiError(400,'Kategori tidak ditemukan');return c.name;} if(category)return category; throw new ApiError(400,'Kategori wajib diisi');}
api.get('/products',asyncRoute(async(_q,res)=>res.json(await prisma.product.findMany({include:productInclude,orderBy:{name:'asc'}}))));
api.get('/pos/products',asyncRoute(async(req,res)=>{ const outletId=String(req.query.outlet_id||''); assertOutlet(req,outletId); const products=await prisma.product.findMany({where:{status:'ACTIVE',outlets:{some:{outletId,isAvailable:true,status:'ACTIVE'}}},include:{categoryRef:true,outlets:{where:{outletId}},variants:{where:{status:'ACTIVE'}},addons:{where:{status:'ACTIVE'}},variantGroups:{orderBy:{sortOrder:'asc'},include:{group:{include:{options:{where:{status:'ACTIVE'},orderBy:{sortOrder:'asc'},include:{outlets:{where:{outletId}}}}}}}}},orderBy:{name:'asc'}});res.json(products.map(p=>{const po=p.outlets[0];if(!po)throw new ApiError(500,'Konfigurasi outlet produk tidak ditemukan');return {...p,basePrice:po.outletPrice??p.basePrice,baseHpp:po.outletHpp??p.baseHpp,masterBasePrice:p.basePrice,masterBaseHpp:p.baseHpp,variantGroups:p.variantGroups.map(vg=>({...vg,group:{...vg.group,options:vg.group.options.filter(o=>!o.outlets[0]||o.outlets[0].status==='ACTIVE').map(o=>({...o,additionalPrice:o.outlets[0]?.additionalPrice??o.additionalPrice,hpp:o.outlets[0]?.hpp??o.hpp,masterAdditionalPrice:o.additionalPrice,masterHpp:o.hpp}))}}))};})); }));
api.post('/products',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>{const d=productInput.parse(req.body);const category=await categoryName(d.categoryId,d.category);const basePrice=d.basePrice??d.variants?.[0]?.sellingPrice??0,baseHpp=d.baseHpp??d.variants?.[0]?.hpp??0;const outletRows=(d.outletPricing??d.outletIds.map(outletId=>({outletId,isAvailable:true,status:'ACTIVE' as const,outletPrice:null,outletHpp:null}))).map(x=>({...x,outletPrice:x.outletPrice??null,outletHpp:x.outletHpp??null}));res.status(201).json(await prisma.product.create({data:{name:d.name,category,categoryId:d.categoryId,description:d.description,imageUrl:d.imageUrl||null,basePrice,baseHpp,status:d.status,variants:{create:d.variants?.length?d.variants:[{variantName:'Base',sellingPrice:basePrice,hpp:baseHpp}]},variantGroups:{create:d.variantGroupIds.map((variantGroupId,i)=>({variantGroupId,sortOrder:i}))},outlets:{create:outletRows.map(x=>({outletId:x.outletId,isAvailable:x.isAvailable,isActive:x.isAvailable,status:x.status,outletPrice:x.outletPrice,outletHpp:x.outletHpp}))}},include:productInclude}));}));
api.put('/products/:id',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>{const d=productInput.partial().parse(req.body);const id=String(req.params.id);const category=d.categoryId||d.category?await categoryName(d.categoryId,d.category):undefined;res.json(await prisma.$transaction(async tx=>{if(d.variantGroupIds){await tx.productVariantGroup.deleteMany({where:{productId:id}});await tx.productVariantGroup.createMany({data:d.variantGroupIds.map((variantGroupId,i)=>({productId:id,variantGroupId,sortOrder:i})),skipDuplicates:true});}if(d.outletPricing){for(const x of d.outletPricing)await tx.productOutlet.upsert({where:{productId_outletId:{productId:id,outletId:x.outletId}},update:{isAvailable:x.isAvailable,isActive:x.isAvailable,status:x.status,outletPrice:x.outletPrice??null,outletHpp:x.outletHpp??null},create:{productId:id,outletId:x.outletId,isAvailable:x.isAvailable,isActive:x.isAvailable,status:x.status,outletPrice:x.outletPrice??null,outletHpp:x.outletHpp??null}});}else if(d.outletIds){await tx.productOutlet.deleteMany({where:{productId:id}});await tx.productOutlet.createMany({data:d.outletIds.map(outletId=>({productId:id,outletId,isAvailable:true,isActive:true,status:'ACTIVE'})),skipDuplicates:true});}return tx.product.update({where:{id},data:{name:d.name,category,categoryId:d.categoryId,description:d.description,imageUrl:d.imageUrl||undefined,basePrice:d.basePrice,baseHpp:d.baseHpp,status:d.status},include:productInclude});}));}));
api.delete('/products/:id',allow('OWNER'),asyncRoute(async(req,res)=>res.json(await prisma.product.update({where:{id:String(req.params.id)},data:{status:'INACTIVE'}}))));
api.get('/products/:id/outlets',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>{const productId=String(req.params.id);const [outlets,rows]=await Promise.all([prisma.outlet.findMany({orderBy:{name:'asc'}}),prisma.productOutlet.findMany({where:{productId},include:{outlet:true}})]);res.json(outlets.map(outlet=>rows.find(r=>r.outletId===outlet.id)||{productId,outletId:outlet.id,outlet,isAvailable:false,isActive:false,outletPrice:null,outletHpp:null,status:'INACTIVE'}));}));
api.put('/products/:id/outlets',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>{const productId=String(req.params.id);const rows=z.object({outlets:z.array(outletPricingInput)}).parse(req.body).outlets;res.json(await prisma.$transaction(async tx=>{for(const x of rows)await tx.productOutlet.upsert({where:{productId_outletId:{productId,outletId:x.outletId}},update:{isAvailable:x.isAvailable,isActive:x.isAvailable,status:x.status,outletPrice:x.outletPrice??null,outletHpp:x.outletHpp??null},create:{productId,outletId:x.outletId,isAvailable:x.isAvailable,isActive:x.isAvailable,status:x.status,outletPrice:x.outletPrice??null,outletHpp:x.outletHpp??null}});return tx.productOutlet.findMany({where:{productId},include:{outlet:true},orderBy:{outlet:{name:'asc'}}});}));}));
api.post('/products/:id/variant-groups',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>{const d=z.object({variantGroupId:z.string(),sortOrder:z.coerce.number().int().default(0)}).parse(req.body);res.status(201).json(await prisma.productVariantGroup.upsert({where:{productId_variantGroupId:{productId:String(req.params.id),variantGroupId:d.variantGroupId}},update:{sortOrder:d.sortOrder},create:{productId:String(req.params.id),...d}}));}));
api.delete('/products/:id/variant-groups/:groupId',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>res.json(await prisma.productVariantGroup.delete({where:{productId_variantGroupId:{productId:String(req.params.id),variantGroupId:String(req.params.groupId)}}}))));
api.post('/products/:id/variants',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>res.status(201).json(await prisma.productVariant.create({data:{productId:String(req.params.id),...z.object({variantName:z.string(),sellingPrice:z.coerce.number(),hpp:z.coerce.number()}).parse(req.body)}}))));
api.put('/variants/:id',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>res.json(await prisma.productVariant.update({where:{id:String(req.params.id)},data:z.object({variantName:z.string().optional(),sellingPrice:z.coerce.number().optional(),hpp:z.coerce.number().optional(),status:z.enum(['ACTIVE','INACTIVE']).optional()}).parse(req.body)}))));
api.delete('/variants/:id',allow('OWNER'),asyncRoute(async(req,res)=>res.json(await prisma.productVariant.update({where:{id:String(req.params.id)},data:{status:'INACTIVE'}}))));
const variantOptionOutletInput=z.object({outletId:z.string(),additionalPrice:z.coerce.number().nonnegative().nullable().optional(),hpp:z.coerce.number().nonnegative().nullable().optional(),status:z.enum(['ACTIVE','INACTIVE']).default('ACTIVE')});
api.get('/variant-options/:id/outlets',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>{const variantOptionId=String(req.params.id);const [outlets,rows]=await Promise.all([prisma.outlet.findMany({orderBy:{name:'asc'}}),prisma.variantOptionOutlet.findMany({where:{variantOptionId},include:{outlet:true}})]);res.json(outlets.map(outlet=>rows.find(r=>r.outletId===outlet.id)||{variantOptionId,outletId:outlet.id,outlet,additionalPrice:null,hpp:null,status:'ACTIVE'}));}));
api.put('/variant-options/:id/outlets',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>{const variantOptionId=String(req.params.id);const rows=z.object({outlets:z.array(variantOptionOutletInput)}).parse(req.body).outlets;res.json(await prisma.$transaction(async tx=>{for(const x of rows)await tx.variantOptionOutlet.upsert({where:{variantOptionId_outletId:{variantOptionId,outletId:x.outletId}},update:{additionalPrice:x.additionalPrice??null,hpp:x.hpp??null,status:x.status},create:{variantOptionId,outletId:x.outletId,additionalPrice:x.additionalPrice??null,hpp:x.hpp??null,status:x.status}});return tx.variantOptionOutlet.findMany({where:{variantOptionId},include:{outlet:true}});}));}));

api.post('/cash-sessions/open',asyncRoute(async(req,res)=>{ const d=z.object({outletId:z.string(),openingCash:z.coerce.number().nonnegative()}).parse(req.body);assertOutlet(req,d.outletId);if(await prisma.cashSession.findFirst({where:{cashierId:req.user!.id,status:'OPEN'}}))throw new ApiError(409,'Masih ada shift yang aktif');res.status(201).json(await prisma.cashSession.create({data:{...d,cashierId:req.user!.id},include:{outlet:true}})); }));
api.get('/cash-sessions/active',asyncRoute(async(req,res)=>res.json(await prisma.cashSession.findFirst({where:{cashierId:req.user!.id,status:'OPEN'},include:{outlet:true,expenses:{where:{status:'ACTIVE'},include:{categoryRef:true},orderBy:{createdAt:'desc'}}}}))));
async function requireActiveShift(req:any,outletId:string,cashSessionId?:string){
  assertOutlet(req,outletId);
  const active=await prisma.cashSession.findFirst({where:{cashierId:req.user!.id,outletId,status:'OPEN'}});
  if(!active)throw new ApiError(400,'Shift belum dibuka. Silakan buka kasir terlebih dahulu.');
  if(cashSessionId&&cashSessionId!==active.id&&!cashSessionId.startsWith('local_'))throw new ApiError(400,'Shift aktif tidak sesuai dengan transaksi.');
  return active;
}
api.post('/cash-sessions/:id/close',asyncRoute(async(req,res)=>{const session=await prisma.cashSession.findFirst({where:{id:String(req.params.id),cashierId:req.user!.id,status:'OPEN'},include:{sales:true,expenses:{where:{status:'ACTIVE'},include:{categoryRef:true},orderBy:{createdAt:'asc'}}}});if(!session)throw new ApiError(404,'Shift aktif tidak ditemukan');const cashSales=session.sales.filter(s=>s.status==='PAID'&&s.paymentMethod==='CASH').reduce((n,s)=>n+Number(s.grandTotal),0);const cashRefund=0;const cashDrawerExpenses=session.expenses.filter(e=>e.paymentSource==='CASH_DRAWER').reduce((n,e)=>n+Number(e.amount),0);const expected=money(Number(session.openingCash)+cashSales-cashRefund-cashDrawerExpenses);const actual=z.object({closingCashActual:z.coerce.number().nonnegative()}).parse(req.body).closingCashActual;const updated=await prisma.cashSession.update({where:{id:session.id},data:{status:'CLOSED',closedAt:new Date(),expectedCash:expected,closingCashActual:actual,variance:money(actual-expected)},include:{outlet:true,cashier:{select:{name:true}},expenses:{where:{status:'ACTIVE'},include:{categoryRef:true},orderBy:{createdAt:'asc'}}}});res.json({...updated,cashSales:money(cashSales),cashRefund:money(cashRefund),cashDrawerExpenses:money(cashDrawerExpenses),expenseDetails:updated.expenses});}));

const expenseCategoryBody=z.object({name:z.string().min(2),description:z.string().nullable().optional(),status:z.enum(['ACTIVE','INACTIVE']).default('ACTIVE'),sortOrder:z.coerce.number().int().default(0)});
api.get('/expense-categories',asyncRoute(async(_req,res)=>res.json(await prisma.expenseCategory.findMany({orderBy:[{sortOrder:'asc'},{name:'asc'}]}))));
api.post('/expense-categories',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>res.status(201).json(await prisma.expenseCategory.create({data:expenseCategoryBody.parse(req.body)}))));
api.put('/expense-categories/:id',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>res.json(await prisma.expenseCategory.update({where:{id:String(req.params.id)},data:expenseCategoryBody.partial().parse(req.body)}))));
api.delete('/expense-categories/:id',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>res.json(await prisma.expenseCategory.update({where:{id:String(req.params.id)},data:{status:'INACTIVE'}}))));

const expenseBody=z.object({categoryId:z.string().optional(),description:z.string().min(2),amount:z.coerce.number().positive(),paymentSource:z.enum(['CASH_DRAWER','NON_CASH','OWNER_TRANSFER']).default('CASH_DRAWER'),note:z.string().nullable().optional(),receiptImageUrl:z.string().nullable().optional()});
const expenseInclude={outlet:true,cashier:{select:{name:true}},cashSession:true,categoryRef:true};
api.get('/expenses',asyncRoute(async(req,res)=>{const where:any={status:req.query.status?String(req.query.status):'ACTIVE'};if(req.query.outlet_id){assertOutlet(req,String(req.query.outlet_id));where.outletId=String(req.query.outlet_id);}else if(req.user!.role!=='OWNER')where.outletId={in:req.user!.outletIds};if(req.query.cash_session_id)where.cashSessionId=String(req.query.cash_session_id);if(req.query.cashier_id)where.cashierId=String(req.query.cashier_id);if(req.query.category_id)where.categoryId=String(req.query.category_id);if(req.query.payment_source)where.paymentSource=String(req.query.payment_source);if(req.query.date)where.createdAt=dayRange(String(req.query.date));res.json(await prisma.expense.findMany({where,include:expenseInclude,orderBy:{createdAt:'desc'}}));}));
api.post('/expenses',asyncRoute(async(req,res)=>{const d=expenseBody.parse(req.body);const active=await prisma.cashSession.findFirst({where:{cashierId:req.user!.id,status:'OPEN'},include:{outlet:true}});if(!active)throw new ApiError(400,'Shift belum dibuka. Silakan buka kasir terlebih dahulu.');assertOutlet(req,active.outletId);const cat=d.categoryId?await prisma.expenseCategory.findUnique({where:{id:d.categoryId}}):null;if(d.categoryId&&!cat)throw new ApiError(400,'Kategori pengeluaran tidak ditemukan');res.status(201).json(await prisma.expense.create({data:{outletId:active.outletId,cashSessionId:active.id,cashierId:req.user!.id,categoryId:cat?.id,categoryName:cat?.name||'Lain-lain',description:d.description,amount:d.amount,paymentSource:d.paymentSource,note:d.note,receiptImageUrl:d.receiptImageUrl},include:expenseInclude}));}));
api.put('/expenses/:id',asyncRoute(async(req,res)=>{const d=expenseBody.partial().parse(req.body);const existing=await prisma.expense.findUnique({where:{id:String(req.params.id)},include:{cashSession:true}});if(!existing)throw new ApiError(404,'Pengeluaran tidak ditemukan');assertOutlet(req,existing.outletId);const isOwner=req.user!.role==='OWNER'||req.user!.role==='SUPERVISOR';if(!isOwner&&(existing.cashierId!==req.user!.id||existing.cashSession.status==='CLOSED'))throw new ApiError(403,'Pengeluaran tidak bisa diedit setelah shift ditutup');const cat=d.categoryId?await prisma.expenseCategory.findUnique({where:{id:d.categoryId}}):null;if(d.categoryId&&!cat)throw new ApiError(400,'Kategori pengeluaran tidak ditemukan');const updated=await prisma.expense.update({where:{id:existing.id},data:{categoryId:d.categoryId??existing.categoryId,categoryName:cat?.name??existing.categoryName,description:d.description,amount:d.amount,paymentSource:d.paymentSource,note:d.note,receiptImageUrl:d.receiptImageUrl},include:expenseInclude});await prisma.auditLog.create({data:{entityType:'EXPENSE',entityId:existing.id,action:'EXPENSE_UPDATED',oldValue:existing as any,newValue:updated as any,changedBy:req.user!.id}});res.json(updated);}));
api.delete('/expenses/:id',asyncRoute(async(req,res)=>{const existing=await prisma.expense.findUnique({where:{id:String(req.params.id)},include:{cashSession:true}});if(!existing)throw new ApiError(404,'Pengeluaran tidak ditemukan');assertOutlet(req,existing.outletId);const isOwner=req.user!.role==='OWNER'||req.user!.role==='SUPERVISOR';if(!isOwner&&(existing.cashierId!==req.user!.id||existing.cashSession.status==='CLOSED'))throw new ApiError(403,'Pengeluaran tidak bisa dihapus setelah shift ditutup');const updated=await prisma.expense.update({where:{id:existing.id},data:{status:'CANCELLED'},include:expenseInclude});await prisma.auditLog.create({data:{entityType:'EXPENSE',entityId:existing.id,action:'EXPENSE_CANCELLED',oldValue:existing as any,newValue:updated as any,changedBy:req.user!.id}});res.json(updated);}));

const couponBody=z.object({couponCode:z.string().min(3).transform(v=>v.toUpperCase()),couponName:z.string().min(2),discountType:z.enum(['NOMINAL','PERCENTAGE']),discountValue:z.coerce.number().positive(),maxDiscountAmount:z.coerce.number().positive().nullable().optional(),minimumTransactionAmount:z.coerce.number().nonnegative().default(0),startDate:z.coerce.date(),endDate:z.coerce.date(),usageLimit:z.coerce.number().int().positive().nullable().optional(),usagePerCustomer:z.coerce.number().int().positive().nullable().optional(),status:z.enum(['ACTIVE','INACTIVE']).default('ACTIVE'),outletIds:z.array(z.string()).default([]),productIds:z.array(z.string()).default([]),categories:z.array(z.string()).default([])}).refine(d=>d.endDate>d.startDate,{message:'Tanggal selesai harus setelah tanggal mulai'}).refine(d=>d.discountType!=='PERCENTAGE'||d.discountValue<=100,{message:'Persentase maksimal 100'});
api.get('/coupons',allow('OWNER','SUPERVISOR'),asyncRoute(async(_q,res)=>res.json(await prisma.coupon.findMany({include:{outlets:{include:{outlet:true}},products:{include:{product:true}},categories:true},orderBy:{createdAt:'desc'}}))));
api.post('/coupons',allow('OWNER'),asyncRoute(async(req,res)=>{const d=couponBody.parse(req.body);const {outletIds,productIds,categories,...data}=d;res.status(201).json(await prisma.coupon.create({data:{...data,outlets:{create:outletIds.map(outletId=>({outletId}))},products:{create:productIds.map(productId=>({productId}))},categories:{create:categories.map(category=>({category}))}},include:{outlets:true,products:true,categories:true}}));}));
api.put('/coupons/:id',allow('OWNER'),asyncRoute(async(req,res)=>{const d=couponBody.parse(req.body);const {outletIds,productIds,categories,...data}=d;const id=String(req.params.id);res.json(await prisma.$transaction(async tx=>{await tx.couponOutlet.deleteMany({where:{couponId:id}});await tx.couponProduct.deleteMany({where:{couponId:id}});await tx.couponCategory.deleteMany({where:{couponId:id}});return tx.coupon.update({where:{id},data:{...data,outlets:{create:outletIds.map(outletId=>({outletId}))},products:{create:productIds.map(productId=>({productId}))},categories:{create:categories.map(category=>({category}))}},include:{outlets:true,products:true,categories:true}});}));}));
api.delete('/coupons/:id',allow('OWNER'),asyncRoute(async(req,res)=>res.json(await prisma.coupon.update({where:{id:String(req.params.id)},data:{status:'INACTIVE'}}))));
api.post('/coupons/validate',asyncRoute(async(req,res)=>{const d=z.object({couponCode:z.string(),outletId:z.string(),items:z.array(z.any())}).parse(req.body);assertOutlet(req,d.outletId);const lines=await priceCart(d.items,d.outletId);const result=await validateCoupon(d.couponCode,d.outletId,lines);res.json({valid:true,coupon:{code:result.coupon.couponCode,name:result.coupon.couponName},discountAmount:result.discountAmount,eligibleAmount:result.eligibleAmount});}));

const saleInput=z.object({outletId:z.string(),cashSessionId:z.string().optional(),customerName:z.string().trim().optional(),items:z.array(z.object({productId:z.string(),variantId:z.string().optional(),selectedVariantOptionIds:z.array(z.string()).optional(),qty:z.number().int().positive(),addonIds:z.array(z.string()).optional(),itemNote:z.string().trim().max(255).optional(),discount:z.object({type:z.enum(['NOMINAL','PERCENTAGE']),value:z.number().nonnegative()}).optional()})).min(1),transactionDiscount:z.object({type:z.enum(['NOMINAL','PERCENTAGE']),value:z.number().nonnegative()}).optional(),couponCode:z.string().optional(),paymentMethod:z.enum(['CASH','QRIS','GOFOOD','GRABFOOD','SHOPEEFOOD','VOUCHER']).optional(),cashReceived:z.number().nonnegative().optional(),idempotencyKey:z.string().min(8).optional()});
async function nextNumber(prefix:string,outletId:string,field:'orderNumber'|'transactionNumber'){
  const outlet=await prisma.outlet.findUniqueOrThrow({where:{id:outletId}});
  const range=dayRange();
  const count=await prisma.sale.count({where:{outletId,createdAt:range,[field]:{not:null}}});
  const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).replaceAll('-','');
  return `${prefix}-${outlet.code}-${date}-${String(count+1).padStart(4,'0')}`;
}
function saleItemCreate(l:any){return {outletId:l.outletId,productId:l.productId,productVariantId:l.variantId,productName:l.productName,variantName:l.variantName,itemNote:l.itemNote,qty:l.qty,sellingPrice:l.unitPrice,hpp:l.hpp,subtotal:l.gross,totalHpp:money(l.hpp*l.qty),grossProfit:money(l.net-l.hpp*l.qty),priceBeforeDiscount:l.unitPrice,discountType:l.discountType,discountValue:l.discountValue,discountAmount:l.discountAmount,subtotalAfterDiscount:l.net,selectedVariantsJson:l.selectedVariants,basePrice:l.basePrice,outletPrice:l.outletPrice,variantPriceTotal:l.variantPriceTotal,finalUnitPrice:l.unitPrice,baseHpp:l.baseHpp,outletHpp:l.outletHpp,variantHppTotal:l.variantHppTotal,finalUnitHpp:l.hpp,addons:{create:l.addons.map((a:any)=>({addonId:a.id,addonName:a.name,price:a.price,hpp:a.hpp}))}};}
async function buildOrderTotals(d:z.infer<typeof saleInput>){
  const lines=await priceCart(d.items,d.outletId);
  const gross=money(lines.reduce((s,l)=>s+l.gross,0)),productDiscount=money(lines.reduce((s,l)=>s+l.discountAmount,0)),afterProduct=money(gross-productDiscount),transactionDiscount=discountAmount(afterProduct,d.transactionDiscount),afterTransaction=money(afterProduct-transactionDiscount);
  const couponResult=d.couponCode?await validateCoupon(d.couponCode,d.outletId,lines):null;
  const couponDiscount=Math.min(afterTransaction,couponResult?.discountAmount||0),grand=money(afterTransaction-couponDiscount),totalHpp=money(lines.reduce((s,l)=>s+l.hpp*l.qty,0));
  return {lines,gross,productDiscount,transactionDiscount,couponResult,couponDiscount,grand,totalHpp};
}
async function createOrder(req:any,d:z.infer<typeof saleInput>,paid:boolean){
  const activeShift=await requireActiveShift(req,d.outletId,d.cashSessionId);
  d={...d,cashSessionId:activeShift.id};
  if(d.idempotencyKey){const key=await prisma.idempotencyKey.findUnique({where:{key:d.idempotencyKey}});if(key){const existing=await prisma.sale.findUnique({where:{id:key.entityId},include:{items:{include:{addons:true}},outlet:true,cashier:{select:{name:true}}}});if(existing)return existing;}}
  const customerName=d.customerName?.trim()||'Walk In';
  const totals=await buildOrderTotals(d);
  if(paid&&!d.paymentMethod) throw new ApiError(400,'Payment method wajib diisi');
  if(paid&&d.paymentMethod==='CASH'&&(d.cashReceived??0)<totals.grand) throw new ApiError(400,'Uang diterima kurang');
  const orderNumber=await nextNumber('ORD',d.outletId,'orderNumber');
  const transactionNumber=paid?await nextNumber('FORU',d.outletId,'transactionNumber'):null;
  return prisma.$transaction(async tx=>{
    const created=await tx.sale.create({data:{orderNumber,transactionNumber,outletId:d.outletId,cashierId:req.user!.id,cashSessionId:d.cashSessionId,customerName,subtotal:totals.gross,discountAmount:money(totals.productDiscount+totals.transactionDiscount+totals.couponDiscount),totalAmount:totals.grand,subtotalBeforeDiscount:totals.gross,productDiscountTotal:totals.productDiscount,transactionDiscountAmount:totals.transactionDiscount,couponCode:totals.couponResult?.coupon.couponCode,couponDiscountAmount:totals.couponDiscount,grandTotal:totals.grand,totalHpp:totals.totalHpp,grossProfit:paid?money(totals.grand-totals.totalHpp):0,paymentMethod:paid?d.paymentMethod:undefined,cashReceived:paid?d.cashReceived:undefined,changeAmount:paid&&d.paymentMethod==='CASH'?money((d.cashReceived||0)-totals.grand):undefined,status:paid?'PAID':'PENDING_PAYMENT',paidAt:paid?new Date():undefined,items:{create:totals.lines.map(saleItemCreate)}},include:{items:{include:{addons:true}},outlet:true,cashier:{select:{name:true}}}});
    if(paid&&totals.couponResult){await tx.coupon.update({where:{id:totals.couponResult.coupon.id},data:{usedCount:{increment:1}}});await tx.couponUsage.create({data:{couponId:totals.couponResult.coupon.id,saleId:created.id,outletId:d.outletId,cashierId:req.user!.id}});}
    if(d.idempotencyKey)await tx.idempotencyKey.create({data:{key:d.idempotencyKey,entityType:paid?'SALE':'ORDER',entityId:created.id}});
    return created;
  });
}
api.post('/orders',asyncRoute(async(req,res)=>res.status(201).json(await createOrder(req,saleInput.parse(req.body),false))));
api.post('/sales',asyncRoute(async(req,res)=>res.status(201).json(await createOrder(req,saleInput.parse(req.body),true))));
api.get('/orders',asyncRoute(async(req,res)=>{const where:any={};if(req.query.status)where.status=String(req.query.status);if(req.query.outlet_id){assertOutlet(req,String(req.query.outlet_id));where.outletId=String(req.query.outlet_id);}else if(req.user!.role!=='OWNER')where.outletId={in:req.user!.outletIds};if(req.query.date)where.createdAt=dayRange(String(req.query.date));if(req.query.customer_name)where.customerName={contains:String(req.query.customer_name),mode:'insensitive'};res.json(await prisma.sale.findMany({where,include:{outlet:true,cashier:{select:{name:true}}},orderBy:{createdAt:'desc'},take:200}));}));
api.get('/orders/:id',asyncRoute(async(req,res)=>{const sale=await prisma.sale.findUnique({where:{id:String(req.params.id)},include:{outlet:true,cashier:{select:{name:true}},items:{include:{addons:true}},printerLogs:{include:{printer:true,user:{select:{name:true}},},orderBy:{printedAt:'desc'}}}});if(!sale)throw new ApiError(404,'Order tidak ditemukan');assertOutlet(req,sale.outletId);res.json(sale);}));
async function updatePendingOrder(req:any,id:string,d:z.infer<typeof saleInput>){
  const existing=await prisma.sale.findUnique({where:{id},include:{items:{include:{addons:true}}}});
  if(!existing) throw new ApiError(404,'Order tidak ditemukan');
  assertOutlet(req,existing.outletId);
  if(existing.status!=='PENDING_PAYMENT') throw new ApiError(400,'Order sudah tidak bisa diedit karena status berubah.');
  if(d.outletId!==existing.outletId) throw new ApiError(400,'Outlet order tidak bisa diubah');
  const activeShift=await requireActiveShift(req,existing.outletId,d.cashSessionId);
  d={...d,cashSessionId:activeShift.id};
  const customerName=d.customerName?.trim()||'Walk In';
  const totals=await buildOrderTotals(d);
  return prisma.$transaction(async tx=>{
    await tx.saleItem.deleteMany({where:{saleId:id}});
    const updated=await tx.sale.update({where:{id},data:{customerName,cashSessionId:d.cashSessionId,subtotal:totals.gross,discountAmount:money(totals.productDiscount+totals.transactionDiscount+totals.couponDiscount),totalAmount:totals.grand,subtotalBeforeDiscount:totals.gross,productDiscountTotal:totals.productDiscount,transactionDiscountAmount:totals.transactionDiscount,couponCode:totals.couponResult?.coupon.couponCode,couponDiscountAmount:totals.couponDiscount,grandTotal:totals.grand,totalHpp:totals.totalHpp,grossProfit:0,paymentMethod:null,cashReceived:null,changeAmount:null,items:{create:totals.lines.map(saleItemCreate)}},include:{items:{include:{addons:true}},outlet:true,cashier:{select:{name:true}}}});
    await tx.auditLog.create({data:{entityType:'ORDER',entityId:id,action:'ORDER_UPDATED',oldValue:{customerName:existing.customerName,grandTotal:existing.grandTotal,items:existing.items},newValue:{customerName,grandTotal:updated.grandTotal,items:updated.items},changedBy:req.user!.id}});
    return updated;
  });
}
api.put('/orders/:id',asyncRoute(async(req,res)=>res.json(await updatePendingOrder(req,String(req.params.id),saleInput.parse(req.body)))));
api.post('/orders/:id/pay',asyncRoute(async(req,res)=>{const body=z.object({paymentMethod:z.enum(['CASH','QRIS','GOFOOD','GRABFOOD','SHOPEEFOOD','VOUCHER']),cashReceived:z.number().nonnegative().optional(),cashSessionId:z.string().optional(),order:z.any().optional()}).parse(req.body);let sale=await prisma.sale.findUnique({where:{id:String(req.params.id)}});if(!sale)throw new ApiError(404,'Order tidak ditemukan');assertOutlet(req,sale.outletId);if(sale.status!=='PENDING_PAYMENT')throw new ApiError(400,'Hanya pending order yang bisa dibayar');const activeShift=await requireActiveShift(req,sale.outletId,body.cashSessionId);if(body.order){sale=await updatePendingOrder(req,sale.id,saleInput.parse({...body.order,outletId:sale.outletId,cashSessionId:activeShift.id}));}const grand=Number(sale.grandTotal);if(body.paymentMethod==='CASH'&&(body.cashReceived??0)<grand)throw new ApiError(400,'Uang diterima kurang');const transactionNumber=await nextNumber('FORU',sale.outletId,'transactionNumber');res.json(await prisma.$transaction(async tx=>{const updated=await tx.sale.update({where:{id:sale!.id},data:{transactionNumber,status:'PAID',paidAt:new Date(),cashSessionId:activeShift.id,paymentMethod:body.paymentMethod,cashReceived:body.cashReceived,changeAmount:body.paymentMethod==='CASH'?money((body.cashReceived||0)-grand):0,grossProfit:money(grand-Number(sale!.totalHpp))},include:{items:{include:{addons:true}},outlet:true,cashier:{select:{name:true}}}});if(updated.couponCode){const coupon=await tx.coupon.findUnique({where:{couponCode:updated.couponCode}});if(coupon){await tx.coupon.update({where:{id:coupon.id},data:{usedCount:{increment:1}}});await tx.couponUsage.create({data:{couponId:coupon.id,saleId:updated.id,outletId:updated.outletId,cashierId:req.user!.id}});}}await tx.auditLog.create({data:{entityType:'ORDER',entityId:updated.id,action:'ORDER_PAID',oldValue:{status:'PENDING_PAYMENT'},newValue:{status:'PAID',transactionNumber},changedBy:req.user!.id}});return updated;}));}));
api.post('/orders/:id/cancel',asyncRoute(async(req,res)=>{const reason=z.object({reason:z.string().min(3).optional()}).parse(req.body).reason;const sale=await prisma.sale.findUnique({where:{id:String(req.params.id)}});if(!sale)throw new ApiError(404,'Order tidak ditemukan');assertOutlet(req,sale.outletId);if(sale.status!=='PENDING_PAYMENT'&&sale.status!=='DRAFT')throw new ApiError(400,'Hanya pending order yang bisa dibatalkan');res.json(await prisma.$transaction(async tx=>{const updated=await tx.sale.update({where:{id:sale.id},data:{status:'CANCELLED',cancelledAt:new Date(),cancelReason:reason||'Cancelled by cashier'}});await tx.auditLog.create({data:{entityType:'ORDER',entityId:sale.id,action:'ORDER_CANCELLED',oldValue:{status:sale.status},newValue:{status:'CANCELLED',reason:updated.cancelReason},changedBy:req.user!.id}});return updated;}));}));
api.get('/sales',asyncRoute(async(req,res)=>{const where:any={status:{in:['PAID','VOID']}};if(req.query.outlet_id){assertOutlet(req,String(req.query.outlet_id));where.outletId=String(req.query.outlet_id);}else if(req.user!.role!=='OWNER')where.outletId={in:req.user!.outletIds};if(req.query.date)where.createdAt=dayRange(String(req.query.date));if(req.query.payment_method)where.paymentMethod=req.query.payment_method;res.json(await prisma.sale.findMany({where,include:{outlet:true,cashier:{select:{name:true}}},orderBy:{createdAt:'desc'},take:200}));}));
api.get('/sales/:id',asyncRoute(async(req,res)=>{const sale=await prisma.sale.findUnique({where:{id:String(req.params.id)},include:{outlet:true,cashier:{select:{name:true}},items:{include:{addons:true}},printerLogs:{include:{printer:true,user:{select:{name:true}},},orderBy:{printedAt:'desc'}}}});if(!sale)throw new ApiError(404,'Transaksi tidak ditemukan');assertOutlet(req,sale.outletId);res.json(sale);}));
api.put('/sales/:id/customer',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>{const customerName=z.object({customerName:z.string().trim().optional()}).parse(req.body).customerName?.trim()||'Walk In';const sale=await prisma.sale.findUnique({where:{id:String(req.params.id)}});if(!sale)throw new ApiError(404,'Transaksi tidak ditemukan');assertOutlet(req,sale.outletId);res.json(await prisma.$transaction(async tx=>{const updated=await tx.sale.update({where:{id:sale.id},data:{customerName}});await tx.auditLog.create({data:{entityType:'SALE',entityId:sale.id,action:'UPDATE_CUSTOMER_NAME',oldValue:{customerName:sale.customerName},newValue:{customerName},changedBy:req.user!.id}});return updated;}));}));
api.post('/sales/:id/void',allow('OWNER','SUPERVISOR'),asyncRoute(async(req,res)=>{const reason=z.object({reason:z.string().min(5)}).parse(req.body).reason;const sale=await prisma.sale.findUnique({where:{id:String(req.params.id)},include:{couponUsage:true}});if(!sale)throw new ApiError(404,'Transaksi tidak ditemukan');assertOutlet(req,sale.outletId);if(sale.status!=='PAID')throw new ApiError(400,'Hanya transaksi paid yang bisa void');res.json(await prisma.$transaction(async tx=>{if(sale.couponUsage){await tx.coupon.update({where:{id:sale.couponUsage.couponId},data:{usedCount:{decrement:1}}});await tx.couponUsage.delete({where:{saleId:sale.id}});}return tx.sale.update({where:{id:sale.id},data:{status:'VOID',voidReason:reason,voidedAt:new Date()}});}));}));

async function logPrintAttempt(saleId:string,userId:string,type:'CUSTOMER_RECEIPT'|'KITCHEN_TICKET'|'CUSTOMER_ITEM_LIST',forcedPrinterId?:string){
  const sale=await prisma.sale.findUnique({where:{id:saleId},include:{outlet:true}});
  if(!sale) throw new ApiError(404,'Transaksi tidak ditemukan');
  const printer=forcedPrinterId?await prisma.printer.findFirst({where:{id:forcedPrinterId,outletId:sale.outletId,status:'ACTIVE'}}):await prisma.printer.findFirst({where:{outletId:sale.outletId,status:'ACTIVE',...(type==='KITCHEN_TICKET'?{isKitchenPrinter:true}:{isCustomerReceipt:true})},orderBy:{createdAt:'asc'}});
  const status=printer?'SUCCESS':'FAILED';
  const errorMessage=printer?null:'Printer aktif belum disetting, gunakan browser print fallback';
  return prisma.printerLog.create({data:{outletId:sale.outletId,saleId:sale.id,printerId:printer?.id,printType:type,status,errorMessage,printedBy:userId},include:{printer:true}});
}
api.post('/print/customer-receipt/:saleId',asyncRoute(async(req,res)=>{const sale=await prisma.sale.findUnique({where:{id:String(req.params.saleId)}});if(!sale)throw new ApiError(404,'Transaksi tidak ditemukan');assertOutlet(req,sale.outletId);res.json(await logPrintAttempt(sale.id,req.user!.id,'CUSTOMER_RECEIPT'));}));
api.post('/print/kitchen-ticket/:saleId',asyncRoute(async(req,res)=>{const sale=await prisma.sale.findUnique({where:{id:String(req.params.saleId)}});if(!sale)throw new ApiError(404,'Transaksi tidak ditemukan');assertOutlet(req,sale.outletId);res.json(await logPrintAttempt(sale.id,req.user!.id,'KITCHEN_TICKET'));}));
api.post('/print/reprint/:saleId',asyncRoute(async(req,res)=>{const d=z.object({printType:z.enum(['CUSTOMER_RECEIPT','KITCHEN_TICKET'])}).parse(req.body);const sale=await prisma.sale.findUnique({where:{id:String(req.params.saleId)}});if(!sale)throw new ApiError(404,'Transaksi tidak ditemukan');assertOutlet(req,sale.outletId);res.json(await logPrintAttempt(sale.id,req.user!.id,d.printType));}));
api.post('/orders/:id/print/customer-item-list',asyncRoute(async(req,res)=>{const sale=await prisma.sale.findUnique({where:{id:String(req.params.id)}});if(!sale)throw new ApiError(404,'Order tidak ditemukan');assertOutlet(req,sale.outletId);res.json(await logPrintAttempt(sale.id,req.user!.id,'CUSTOMER_ITEM_LIST'));}));
api.post('/orders/:id/print/kitchen-ticket',asyncRoute(async(req,res)=>{const sale=await prisma.sale.findUnique({where:{id:String(req.params.id)}});if(!sale)throw new ApiError(404,'Order tidak ditemukan');assertOutlet(req,sale.outletId);res.json(await logPrintAttempt(sale.id,req.user!.id,'KITCHEN_TICKET'));}));

const syncRow=z.object({local_id:z.string(),action:z.enum(['CREATE','UPDATE','DELETE','PAY','CANCEL','VOID','CLOSE_SHIFT','PRINT']),idempotency_key:z.string().min(8),payload_hash:z.string().optional(),payload:z.any()});
const syncPushBody=z.object({orders:z.array(syncRow).default([]),sales:z.array(syncRow).default([]),expenses:z.array(syncRow).default([]),cash_sessions:z.array(syncRow).default([]),printer_logs:z.array(syncRow).default([]),audit_logs:z.array(syncRow).default([]),variant_options:z.array(syncRow).default([])});
async function existingByKey(key:string){const found=await prisma.idempotencyKey.findUnique({where:{key}});return found?{local_id:null,server_id:found.entityId,sync_status:'SYNCED' as const,duplicate:true}:null;}
async function rememberKey(tx:any,key:string,entityType:string,entityId:string,payloadHash?:string){await tx.idempotencyKey.create({data:{key,entityType,entityId,payloadHash}});}
async function syncMasterData(req:any, incremental=false){
  const outletWhere=req.user!.role==='OWNER'?{}:{id:{in:req.user!.outletIds}};
  const outletIds=req.user!.role==='OWNER'?undefined:req.user!.outletIds;
  const since=req.query.last_sync_at?new Date(String(req.query.last_sync_at)):null;
  const changed=(where:any={})=>incremental&&since&&!Number.isNaN(since.getTime())?{...where,updatedAt:{gt:since}}:where;
  const [outlets,categories,products,variantGroups,coupons,printers,user]=await Promise.all([
    prisma.outlet.findMany({where:changed(outletWhere),orderBy:{name:'asc'}}),
    prisma.category.findMany({where:changed({status:'ACTIVE'}),orderBy:[{sortOrder:'asc'},{name:'asc'}]}),
    prisma.product.findMany({where:changed({status:'ACTIVE',...(outletIds?{outlets:{some:{outletId:{in:outletIds},isAvailable:true,status:'ACTIVE'}}}:{})}),include:productInclude,orderBy:{name:'asc'}}),
    prisma.variantGroup.findMany({where:changed({status:'ACTIVE'}),include:{options:{where:{status:'ACTIVE'},orderBy:{sortOrder:'asc'},include:{outlets:true}}},orderBy:{name:'asc'}}),
    prisma.coupon.findMany({where:changed({status:'ACTIVE'}),include:{outlets:true,products:true,categories:true}}),
    prisma.printer.findMany({where:changed(req.user!.role==='OWNER'?{}:{outletId:{in:req.user!.outletIds}}),orderBy:{createdAt:'desc'}}),
    prisma.user.findUnique({where:{id:req.user!.id},select:{id:true,name:true,username:true,role:true,outlets:true}})
  ]);
  return {outlets,categories,products,variantGroups,coupons,printers,user,incremental,serverTime:new Date().toISOString()};
}
api.get('/sync/master-data',asyncRoute(async(req,res)=>res.json(await syncMasterData(req))));
api.get('/sync/bootstrap',asyncRoute(async(req,res)=>res.json(await syncMasterData(req))));
api.get('/sync/pull',asyncRoute(async(req,res)=>res.json(await syncMasterData(req,true))));
api.get('/sync/status',asyncRoute(async(req,res)=>{res.json({online:true,serverTime:new Date().toISOString()});}));
api.post('/sync/status',asyncRoute(async(req,res)=>{const d=z.object({action:z.enum(['MANUAL_SYNC','AUTO_SYNC','SYNC_FAILED']),startedAt:z.string().optional(),finishedAt:z.string().optional(),duration:z.number().optional(),recordsUploaded:z.number().optional(),recordsDownloaded:z.number().optional(),failedRecords:z.number().optional(),device:z.string().optional(),error:z.string().optional()}).parse(req.body);await prisma.auditLog.create({data:{entityType:'SYNC',entityId:req.user!.id,action:d.action,oldValue:Prisma.JsonNull,newValue:d as any,changedBy:req.user!.id}});res.json({ok:true});}));
api.post('/sync/push',asyncRoute(async(req,res)=>{
  const startedAt=new Date();
  const d=syncPushBody.parse(req.body);
  const results:any[]=[];
  let uploaded=0,failed=0;
  async function pushResult(row:z.infer<typeof syncRow>,entityType:string,fn:()=>Promise<any>){
    try{const duplicate=await existingByKey(row.idempotency_key);if(duplicate){results.push({...duplicate,local_id:row.local_id});return;}const created=await fn();uploaded++;results.push({local_id:row.local_id,server_id:created.id,order_number:created.orderNumber,transaction_number:created.transactionNumber,sync_status:'SYNCED'});}
    catch(error){failed++;results.push({local_id:row.local_id,entity_type:entityType,sync_status:'FAILED',error:(error as Error).message});}
  }
  for(const row of d.orders)await pushResult(row,'ORDER',()=>createOrder(req,saleInput.parse({...row.payload,idempotencyKey:row.idempotency_key}),false));
  for(const row of d.sales)await pushResult(row,'SALE',()=>createOrder(req,saleInput.parse({...row.payload,idempotencyKey:row.idempotency_key}),true));
  for(const row of d.expenses)await pushResult(row,'EXPENSE',async()=>{const body=expenseBody.parse(row.payload);const active=await prisma.cashSession.findFirst({where:{cashierId:req.user!.id,status:'OPEN'}});const outletId=row.payload.outletId||active?.outletId;if(!outletId)throw new ApiError(400,'Outlet pengeluaran offline tidak ditemukan');assertOutlet(req,outletId);const cat=body.categoryId?await prisma.expenseCategory.findUnique({where:{id:body.categoryId}}):null;return prisma.$transaction(async tx=>{const expense=await tx.expense.create({data:{outletId,cashSessionId:row.payload.cashSessionId||active?.id,cashierId:req.user!.id,categoryId:cat?.id,categoryName:cat?.name||row.payload.categoryName||'Lain-lain',description:body.description,amount:body.amount,paymentSource:body.paymentSource,note:body.note,receiptImageUrl:body.receiptImageUrl}});await rememberKey(tx,row.idempotency_key,'EXPENSE',expense.id,row.payload_hash);return expense;});});
  for(const row of d.cash_sessions)await pushResult(row,'CASH_SESSION',async()=>{const payload=z.object({outletId:z.string(),openingCash:z.coerce.number().nonnegative(),closingCashActual:z.coerce.number().nonnegative().optional(),expectedCash:z.coerce.number().optional(),variance:z.coerce.number().optional(),status:z.enum(['OPEN','CLOSED']).optional()}).parse(row.payload);assertOutlet(req,payload.outletId);return prisma.$transaction(async tx=>{const session=await tx.cashSession.create({data:{outletId:payload.outletId,cashierId:req.user!.id,openingCash:payload.openingCash,closingCashActual:payload.closingCashActual,expectedCash:payload.expectedCash,variance:payload.variance,status:payload.status||'OPEN',closedAt:payload.status==='CLOSED'?new Date():undefined}});await rememberKey(tx,row.idempotency_key,'CASH_SESSION',session.id,row.payload_hash);return session;});});
  for(const row of d.variant_options)await pushResult(row,'VARIANT_OPTION',async()=>{const payload=z.object({local_id:z.string(),server_id:z.string().nullable().optional(),variant_group_local_id:z.string(),variant_group_server_id:z.string().nullable().optional(),name:z.string().min(1),additional_price:z.coerce.number().nonnegative().default(0),hpp:z.coerce.number().nonnegative().default(0),sort_order:z.coerce.number().int().default(0),status:z.enum(['ACTIVE','INACTIVE','DELETED']).default('ACTIVE'),deleted_at:z.string().nullable().optional()}).parse(row.payload);const groupId=payload.variant_group_server_id||payload.variant_group_local_id;if(!groupId||String(groupId).startsWith('local_'))throw new ApiError(409,'Variant group belum tersinkron. Sync group terlebih dahulu.');return prisma.$transaction(async tx=>{let option;if(row.action==='CREATE'){option=await tx.variantOption.create({data:{variantGroupId:groupId,name:payload.name,additionalPrice:payload.additional_price,hpp:payload.hpp,sortOrder:payload.sort_order,status:payload.status==='DELETED'?'INACTIVE':payload.status}});}else{const optionId=payload.server_id||payload.local_id;if(!optionId||String(optionId).startsWith('local_'))throw new ApiError(409,'Variant option server_id belum ada.');option=row.action==='DELETE'?await tx.variantOption.update({where:{id:optionId},data:{status:'INACTIVE'}}):await tx.variantOption.update({where:{id:optionId},data:{name:payload.name,additionalPrice:payload.additional_price,hpp:payload.hpp,sortOrder:payload.sort_order,status:payload.status==='DELETED'?'INACTIVE':payload.status}});}await rememberKey(tx,row.idempotency_key,'VARIANT_OPTION',option.id,row.payload_hash);return option;});});
  for(const row of d.printer_logs)await pushResult(row,'PRINTER_LOG',async()=>prisma.$transaction(async tx=>{const sale=await tx.sale.findUnique({where:{id:String(row.payload.saleId)}});if(!sale)throw new ApiError(400,'Sale printer log tidak ditemukan');assertOutlet(req,sale.outletId);const log=await tx.printerLog.create({data:{outletId:sale.outletId,saleId:sale.id,printerId:row.payload.printerId,printType:row.payload.printType,status:row.payload.status||'SUCCESS',errorMessage:row.payload.errorMessage,printedBy:req.user!.id}});await rememberKey(tx,row.idempotency_key,'PRINTER_LOG',log.id,row.payload_hash);return log;}));
  for(const row of d.audit_logs)await pushResult(row,'AUDIT_LOG',async()=>prisma.$transaction(async tx=>{const log=await tx.auditLog.create({data:{entityType:row.payload.entityType||'OFFLINE',entityId:row.payload.entityId||row.local_id,action:row.payload.action||row.action,oldValue:row.payload.oldValue,newValue:row.payload.newValue,changedBy:req.user!.id}});await rememberKey(tx,row.idempotency_key,'AUDIT_LOG',log.id,row.payload_hash);return log;}));
  await prisma.auditLog.create({data:{entityType:'SYNC',entityId:req.user!.id,action:failed?'SYNC_FAILED':'MANUAL_SYNC',oldValue:Prisma.JsonNull,newValue:{started_at:startedAt,finished_at:new Date(),duration:Date.now()-startedAt.getTime(),records_uploaded:uploaded,records_downloaded:0,failed_records:failed,device:req.headers['user-agent']},changedBy:req.user!.id}});
  res.json({ok:failed===0,uploaded,failed,results});
}));

async function report(req:any){const range=req.query.date?dayRange(String(req.query.date)):dayRange();const baseWhere:any={createdAt:range};if(req.query.outlet_id){assertOutlet(req,String(req.query.outlet_id));baseWhere.outletId=String(req.query.outlet_id);}else if(req.user.role!=='OWNER')baseWhere.outletId={in:req.user.outletIds};const sales=await prisma.sale.findMany({where:{...baseWhere,status:'PAID'},include:{items:true,outlet:true}});const expenses=await prisma.expense.findMany({where:{...baseWhere,status:'ACTIVE'},include:{categoryRef:true,outlet:true}});const pending=await prisma.sale.aggregate({where:{...baseWhere,status:'PENDING_PAYMENT'},_count:true,_sum:{grandTotal:true}});const sum=(key:string)=>money(sales.reduce((n,s)=>n+Number((s as any)[key]),0));const gross=sum('subtotalBeforeDiscount'),productDiscount=sum('productDiscountTotal'),transactionDiscount=sum('transactionDiscountAmount'),couponDiscount=sum('couponDiscountAmount'),net=sum('grandTotal'),hpp=sum('totalHpp');const cashSales=money(sales.filter(s=>s.paymentMethod==='CASH').reduce((n,s)=>n+Number(s.grandTotal),0));const cashDrawerExpense=money(expenses.filter(e=>e.paymentSource==='CASH_DRAWER').reduce((n,e)=>n+Number(e.amount),0));const nonCashExpense=money(expenses.filter(e=>e.paymentSource==='NON_CASH').reduce((n,e)=>n+Number(e.amount),0));const ownerTransferExpense=money(expenses.filter(e=>e.paymentSource==='OWNER_TRANSFER').reduce((n,e)=>n+Number(e.amount),0));const expenseByCategory=[...expenses.reduce((m,e)=>{const k=e.categoryName||e.categoryRef?.name||'Lain-lain';m.set(k,(m.get(k)||0)+Number(e.amount));return m;},new Map<string,number>()).entries()].map(([category,amount])=>({category,amount:money(amount)}));return {grossSales:gross,productDiscount,transactionDiscount,couponDiscount,netSales:net,paidSalesAmount:net,pendingOrdersCount:pending._count,pendingOrdersAmount:money(Number(pending._sum.grandTotal||0)),totalHpp:hpp,grossProfit:money(net-hpp),grossMargin:net?money((net-hpp)/net*100):0,totalTransactions:sales.length,averageTicket:sales.length?money(net/sales.length):0,payments:Object.fromEntries(['CASH','QRIS','GOFOOD','GRABFOOD','SHOPEEFOOD','VOUCHER'].map(p=>[p,money(sales.filter(s=>s.paymentMethod===p).reduce((n,s)=>n+Number(s.grandTotal),0))])),cashDrawerExpense,nonCashExpense,ownerTransferExpense,totalExpense:money(expenses.reduce((n,e)=>n+Number(e.amount),0)),expenseByCategory,netCashMovement:money(cashSales-cashDrawerExpense),sales};}
api.get('/reports/daily',asyncRoute(async(req,res)=>{const r=await report(req);res.json({...r,sales:undefined});}));
api.get('/reports/dashboard',asyncRoute(async(req,res)=>{const r=await report(req);const outlets=new Map<string,any>();for(const s of r.sales){const x=outlets.get(s.outletId)||{outlet:s.outlet.name,netSales:0,transactions:0,grossProfit:0};x.netSales+=Number(s.grandTotal);x.transactions++;x.grossProfit+=Number(s.grossProfit);outlets.set(s.outletId,x);}res.json({...r,sales:undefined,outlets:[...outlets.values()].map(x=>({...x,averageTicket:money(x.netSales/x.transactions)}))});}));
api.get('/reports/products',asyncRoute(async(req,res)=>{const r=await report(req);const map=new Map<string,any>();for(const s of r.sales)for(const i of s.items){const x=map.get(i.productId)||{productName:i.productName,qty:0,revenue:0,hpp:0};x.qty+=i.qty;x.revenue+=Number(i.subtotalAfterDiscount);x.hpp+=Number(i.totalHpp);map.set(i.productId,x);}res.json([...map.values()].map(x=>({...x,grossProfit:money(x.revenue-x.hpp)})).sort((a,b)=>b.qty-a.qty));}));
api.get('/reports/outlets',asyncRoute(async(req,res)=>{const r=await report(req);const map=new Map<string,any>();for(const s of r.sales){const x=map.get(s.outletId)||{outlet:s.outlet.name,grossSales:0,netSales:0,discount:0,grossProfit:0,transactions:0};x.grossSales+=Number(s.subtotalBeforeDiscount);x.netSales+=Number(s.grandTotal);x.discount+=Number(s.discountAmount);x.grossProfit+=Number(s.grossProfit);x.transactions++;map.set(s.outletId,x);}res.json([...map.values()]);}));

app.use((err:any,_req:any,res:any,_next:any)=>{if(err instanceof z.ZodError)return res.status(400).json({message:err.issues[0]?.message||'Data tidak valid',issues:err.issues});if(err instanceof ApiError)return res.status(err.status).json({message:err.message});if(err instanceof Prisma.PrismaClientKnownRequestError&&err.code==='P2002')return res.status(409).json({message:'Data unik sudah digunakan'});console.error(err);res.status(500).json({message:'Terjadi kesalahan pada server'});});
const port=Number(process.env.PORT||4000);app.listen(port,()=>console.log(`FORU POS API running on http://localhost:${port}`));
