import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../api';
import { useOutlet } from '../OutletContext';
import { toast } from '../toast';

type Partner={id:string;outletId:string;name:string;type:'INTERNAL_KITCHEN'|'EXTERNAL_VENDOR';contactName?:string|null;phone?:string|null;address?:string|null;notes?:string|null;sortOrder:number;status:string};
export default function ProductionPartnersPage(){
  const {outletList}=useOutlet();const [outletId,setOutletId]=useState('');const [rows,setRows]=useState<Partner[]>([]);const [edit,setEdit]=useState<Partial<Partner>|null>(null);const [error,setError]=useState('');
  useEffect(()=>{if(!outletId&&outletList[0])setOutletId(outletList[0].id);},[outletList,outletId]);
  const load=()=>outletId?api<Partner[]>(`/production-partners?outletId=${encodeURIComponent(outletId)}`).then(setRows):Promise.resolve();
  useEffect(()=>{load().catch(e=>setError(e.message));},[outletId]);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(edit?.id?`/production-partners/${edit.id}`:'/production-partners',{method:edit?.id?'PUT':'POST',body:JSON.stringify({outletId,name:f.get('name'),type:f.get('type'),contactName:f.get('contactName')||null,phone:f.get('phone')||null,address:f.get('address')||null,notes:f.get('notes')||null,sortOrder:Number(f.get('sortOrder')||0),status:f.get('status')||'ACTIVE'})});setEdit(null);await load();toast.success('Mitra Produksi berhasil disimpan.');}catch(e){setError((e as Error).message);}}
  return <div className="p-4 lg:p-8"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">Mitra Produksi</h1><p className="text-slate-500">Kelola dapur internal dan vendor produksi per outlet.</p></div><button className="btn-primary" onClick={()=>setEdit({type:'INTERNAL_KITCHEN',status:'ACTIVE',sortOrder:0})}>+ Tambah Mitra</button></div>
    <label className="mb-4 block max-w-md">Outlet<select className="input" value={outletId} onChange={e=>setOutletId(e.target.value)}>{outletList.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(row=><article className="card p-5" key={row.id}><div className="flex justify-between gap-3"><div><span className="text-xs font-black text-brand-700">{row.type==='EXTERNAL_VENDOR'?'VENDOR EKSTERNAL':'DAPUR INTERNAL'}</span><h2 className="text-xl font-black">{row.name}</h2></div><span className="pill bg-slate-100">{row.status}</span></div><p className="mt-3 text-sm">PIC: {row.contactName||'-'}<br/>WhatsApp: {row.phone||'-'}</p><p className="mt-2 text-xs text-slate-500">{row.address||row.notes||'Tanpa keterangan'}</p><button className="mt-4 font-bold text-brand-700" onClick={()=>setEdit(row)}>Edit</button></article>)}</div>
    {edit&&<div className="fixed inset-0 z-[70] grid place-items-center overflow-auto bg-black/40 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-3xl bg-white p-6"><div className="mb-4 flex justify-between"><h2 className="text-2xl font-black">{edit.id?'Edit':'Tambah'} Mitra Produksi</h2><button type="button" onClick={()=>setEdit(null)}>×</button></div>{[['name','Nama mitra'],['contactName','Nama PIC'],['phone','No. WhatsApp'],['address','Alamat'],['notes','Catatan'],['sortOrder','Urutan']].map(([name,label])=><label className="mb-3 block" key={name}><span className="label">{label}</span><input className="input" name={name} type={name==='sortOrder'?'number':'text'} defaultValue={(edit as any)[name]||''} required={name==='name'}/></label>)}<label className="label">Tipe</label><select className="input mb-3" name="type" defaultValue={edit.type||'INTERNAL_KITCHEN'}><option value="INTERNAL_KITCHEN">Dapur Internal</option><option value="EXTERNAL_VENDOR">Vendor Eksternal</option></select><label className="label">Status</label><select className="input mb-4" name="status" defaultValue={edit.status||'ACTIVE'}><option>ACTIVE</option><option>INACTIVE</option></select><button className="btn-primary w-full">Simpan Mitra</button></form></div>}
  </div>;
}
